### ISSUE TITLE
Using Kubeadm

### ISSUE THREAD

**Issue by yelhouti** [kube-hetzner/kube-hetzner#132]
First of all, congratulation for the great work.

I was looking for a project like this to bootstrap a k8s cluster on hetzner cloud with support for csi and ccm and this looks great.

However I am used to working with kubeadm (through kubespray) which seems better suited for production use and heavy workload.

Are you planning to add support for kubeadm ? (I understand automatic upgrades might be more difficult to implement).

**Comment by mysticaltech** [comment]
Hello @yelhouti, I understand your concern, but trust me when I tell you that k3s is definitely suited for production and heavy workloads. It basically shares the exact same source with a few adjustments and is constantly synced with upstream Kubernetes, probably on a daily if not hourly basis. 

This explanatory video will make everything clear: https://youtu.be/FmLna7tHDRc. There is absolutely no reason why not use k3s instead of kubeadm, even if you go planetary scale. It's the same codebase, just packaged differently, more optimized, and more agile (much simpler upgrades).

**Comment by mysticaltech** [comment]
However, if you want, you could replace the MicroOS image with one that contains Kubeadm installed already. So it which case you would need to rebuild a similar project, but you could definitely reuse the host module here https://github.com/kube-hetzner/kube-hetzner/tree/master/modules/host.

This is the MicrosOS we use today:

https://github.com/kube-hetzner/kube-hetzner/blob/master/modules/host/main.tf#L51

However, you could replace the image with [openSUSE-MicroOS.x86_64-Kubic-kubeadm-OpenStack-Cloud](https://download.opensuse.org/tumbleweed/appliances/openSUSE-MicroOS.x86_64-Kubic-kubeadm-OpenStack-Cloud.qcow2.meta4).

IMHO, definitely not needed! :)

**Comment by mysticaltech** [comment]
Btw, https://www.civo.com/, which serves companies like Walmart and Verizon, runs its operation entirely on k3s.

**Comment by yelhouti** [comment]
@mysticaltech thanks a lot for all the feedback :)
