### ISSUE TITLE
feature request: custom firewall

### ISSUE THREAD

**Issue by exocode** [kube-hetzner/kube-hetzner#64]
Just a suggestion (but a really nice to have):

### Feature Custom Firewalls

In order to keep variables, where they should be, and never touch the `.tf` files,
it would be nice if there is a place, where custom ports can be managed:

currently I do this in `main.tf`

 ```terraform
resource "hcloud_firewall" "k3s" {
  name = "k3s-firewall"

## My Custom firewall rule
# Postgres
  rule {
    direction = "out"
    protocol  = "tcp"
    port      = "5432"
    destination_ips = [
      "0.0.0.0/0"
    ]
  }
```

Maybe that part could be "outsourced" in a `firewall.tf`-file or in a nested array in variables.

edit: removed "multiple feature" like mentioned in the first comment

**Comment by phaer** [comment]
Thanks for the suggestions! I think its preferable to open one issue per feature request than to use subheadings, as it can quickly become tedious the follow the discussion on each feature suggestion otherwise.

### Custom firewall rules.

I think the most flexible solution would be to use kube-hetzner as a submodule in your own terraform project. That would allow you to add any additional terraform resources you'd like, including hetzner firewall rules.

That being said, a pull request allowing opening up additional outgoing ports seems useful to me - feel free to open one!

### Nodepools

Sounds like a useful feature to me, but might be a bit tricky to implement in terraform. PR most welcome, i'd say! :)

**Comment by exocode** [comment]
I will open a second one.

**Comment by mysticaltech** [comment]
@exocode Please try again with the new setup, we've improved a lot! About this feature, also do not hesitate to send us a PR, it seems like a low-hanging fruit! 🙏
